---
 - name: Ensure that the repositories are update
   yum: 
     update_cache: yes

 - name: Install all the essential packages
   yum:
     name: "{{ ','.join(pkgs_list) }}"
     state: latest
 
 - name: Adding Linx User
   user: 
     name: "{{ item.username }}" 
     comment: "{{ item.username }}@github"
     shell: /bin/bash
     state: "{{ item.state | default('present') }}"
   with_items: "{{ users_list }}"

 - name: Create .ssh directory
   file: 
     path: /home/{{ item.username }}/.ssh 
     state: directory 
     owner: "{{ item.username }}"
     group: "{{ item.username }}"
     mode: 0700
   when: item.get('state', 'present') == 'present'
   with_items: "{{ users_list }}"

 - name: Assign sudo role to the admin users
   copy: 
     content: "{{ item.username }} ALL=(ALL) NOPASSWD:ALL" 
     dest: /etc/sudoers.d/99-{{ item.username }}
   when: item.type is defined and item.type == 'admin' and item.get('state', 'present') == 'present'
   with_items: "{{ users_list }}"
