---
- name: Install WordPress, Nginx, and PHP-FPM
  hosts: all
  remote_user: centos
  become: true
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
